//==============================================================================
// File Name   : epl_Ffbit_n_sub.v
// Created     : 2026/01/08
// Author      : EPL Lab Memory Test and Repair Group
// Version     : 1.1
//
// Description :
//   Normal FFRAM bit-cell behavioral model (DFF-based, synthesizable).
//
//   - One bit storage implemented by a single D flip-flop.
//   - Write occurs on posedge pClk_i when pWec_i is asserted.
//   - pWec_i is assumed to already include all necessary wordline / column
//     gating generated by upstream logic.
//   - Read is implicit: stored value is continuously visible on pDtoc_o.
//   - Active-low asynchronous reset clears the stored bit to 0.
//
// I/O Description :
//   pClk_i   : Clock input
//   nRst_i   : Asynchronous active-low reset
//   pWec_i   : Write enable (column-level, already gated)
//   pDic_i   : Data input (1-bit)
//   pDtoc_o  : Data output (stored bit)
//
// Notes :
//   - This module represents a normal (fault-free) memory bit-cell.
//   - Wordline and column selection are handled at array/column level.
//   - This model is intended for functional and synthesis verification.
//==============================================================================

module epl_Ffbit_n_sub (
           input  wire                     pClk_i,
           input  wire                     nRst_i,
           input  wire                     pWec_i,
           input  wire                     pDic_i,
           output reg                      pDtoc_o
       );

always @(posedge pClk_i or negedge nRst_i)
begin
    if (!nRst_i)
        pDtoc_o <= 1'b0;
    else if (pWec_i)
    begin
        pDtoc_o <= pDic_i;
    end
end

endmodule
