/******************************************************************************
* File Name   : epl_Read_Mux_sub.v
* Created     : 2026/01/08
* Author      : EPL Lab Memory Test and Repair Group
* Version     : 0.2
*
* Description :
*   Read Mux sub-module
*   - pAcy_i is a one-hot column select signal (generated by upstream/Compiler).
*   - Reconstruct pDo_o (TWORD_WIDTH bits) from pDto_i (COLUMN bits) based on pAcy_i:
*       pAcy_i = 2'b01 -> select even columns: 0,2,4,6,8,10,12  -> pDo_o[0:6]
*       pAcy_i = 2'b10 -> select odd  columns: 1,3,5,7,9,11,13  -> pDo_o[0:6]
*   - Registered outputs: pDo_o & pRead1_o aligned on same clock edge (gated by pRead01_i).
*
* Notes :
*   - For invalid (non one-hot) pAcy_i values, mux result will be all-0.
*   - pRead01_i is the read-valid from previous stage (stage0 -> this stage).
*   - When pRead01_i = 0, pRead1_o will be 0 and pDo_o is cleared to 0.
*
* Modification History :
*   Date        Version    Author                               Description
*   ----------  ---------  -----------------------------------  ----------------
*   2026/01/08  0.1        EPL Lab Memory Test and Repair Group  Skeleton created
*   2026/01/12  0.2        EPL Lab Memory Test and Repair Group  Implemented case-based read mux + reg outputs
******************************************************************************/
`include "EPLFFRAM02_spec.vh"

module epl_Read_Mux_sub (
           input  wire [`COLUMN-1:0]      pDto_i,
           input  wire [`ADDR_AYO-1:0]     pAcy2_i,
           output reg  [`TWORD_WIDTH-1:0]  pDo_o,
           output reg                      pRead1_o,
           input  wire                     pClk_i,
           input  wire                     nRst_i,
           input  wire                     pRead01_i
       );

reg [`TWORD_WIDTH-1:0] pDomux_r;

// ------------------------------------------------------------
// Read data mux (case table; Column_Access-style; Python-friendly)
// pAcy_i is assumed one-hot. Invalid values -> all-0.
// ------------------------------------------------------------
always @(*)
begin
    pDomux_r = {`TWORD_WIDTH{1'b0}};

    case (pAcy2_i)
        2'b01:
        begin
            // even columns
            pDomux_r[0] = pDto_i[0];
            pDomux_r[1] = pDto_i[2];
            pDomux_r[2] = pDto_i[4];
            pDomux_r[3] = pDto_i[6];
            pDomux_r[4] = pDto_i[8];
            pDomux_r[5] = pDto_i[10];
            pDomux_r[6] = pDto_i[12];
        end

        2'b10:
        begin
            // odd columns
            pDomux_r[0] = pDto_i[1];
            pDomux_r[1] = pDto_i[3];
            pDomux_r[2] = pDto_i[5];
            pDomux_r[3] = pDto_i[7];
            pDomux_r[4] = pDto_i[9];
            pDomux_r[5] = pDto_i[11];
            pDomux_r[6] = pDto_i[13];
        end

        default:
        begin
            pDomux_r = {`TWORD_WIDTH{1'b0}};
        end
    endcase
end

// ------------------------------------------------------------
// Registered outputs (pDo_o & pRead1_o aligned)
// ------------------------------------------------------------
always @(posedge pClk_i or negedge nRst_i)
begin
    if (!nRst_i)
    begin
        pDo_o    <= {`TWORD_WIDTH{1'b0}};
        pRead1_o <= 1'b0;
    end
    else if (pRead01_i)
    begin
        pDo_o    <= pDomux_r;
        pRead1_o <= 1'b1;
    end
    else
    begin
        pRead1_o <= 1'b0;
        pDo_o    <={`TWORD_WIDTH{1'b0}};
    end
end

endmodule

